#!/usr/bin/env bash
# Regenerate forge_sources.luau by embedding the REAL Forge source verbatim.
# The test harness runs these strings under luau (which has no io.open), so this is
# how the actual production code gets executed by the tests — not a reimplementation.
set -euo pipefail
cd "$(dirname "$0")"

SRC=(../src/Bridge/Protocol.lua ../src/Bridge/Bridge.lua ../src/State/Store.lua)
KEYS=(Protocol Bridge Store)

# Guard against the long-bracket delimiter appearing in source.
for f in "${SRC[@]}"; do
  if grep -q ']===]' "$f"; then echo "ERROR: ]===] collision in $f" >&2; exit 1; fi
done

{
  echo '-- AUTO-GENERATED by gen_sources.sh — do not edit. Run ./gen_sources.sh to refresh.'
  echo '-- Embeds the REAL Forge source verbatim so the harness executes production code.'
  echo 'return {'
  for i in "${!SRC[@]}"; do
    printf '  ["%s"] = [===[\n' "${KEYS[$i]}"
    cat "${SRC[$i]}"
    printf '\n]===],\n'
  done
  echo '}'
} > forge_sources.luau

echo "Regenerated forge_sources.luau from ${#SRC[@]} source files."
